=== fpoulin/json-shapeshifter/src/main/resources/schemas/testComplex.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"someEventString": {
			"type": "string"
		},
		"someEventInteger": {
			"type": "integer"
		},
		"someEventStringArray": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"someEventIntegerArray": {
			"type": "array",
			"items": {
				"type": "integer"
			}
		},
		"simpleEventObject": {
			"type": "object",
			"properties": {
				"stringEventProperty": {
					"type": "string"
				},
				"integerEventProperty": {
					"type": "integer"
				}
			},
			"additionalProperties" : false,
			"required": ["stringEventProperty", "integerEventProperty"]
		},
		"arrayOfEventObjects": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"stringEventProperty": {
						"type": "string"
					},
					"integerEventProperty": {
						"type": "integer"
					}
				},
				"additionalProperties" : false,
				"required": ["stringEventProperty", "integerEventProperty"]
			}
		},
		"complexEventObject": {
			"type": "object",
			"properties": {
				"objectEventProperty": {
					"type": "object",
					"properties": {
						"stringEventProperty": {
							"type": "string"
						},
						"integerEventProperty": {
							"type": "integer"
						}
					},
					"additionalProperties" : false,
					"required": ["stringEventProperty", "integerEventProperty"]
				},
				"arrayEventProperty": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"stringEventProperty": {
								"type": "string"
							},
							"integerEventProperty": {
								"type": "integer"
							}
						},
						"additionalProperties" : false,
						"required": ["stringEventProperty", "integerEventProperty"]
					}
				}
			},
			"additionalProperties" : false,
			"required": ["objectEventProperty", "arrayEventProperty"]
		}
	},
	"additionalProperties" : false,
	"required": ["someEventString", "someEventInteger", "someEventStringArray", "someEventIntegerArray", "simpleEventObject", "arrayOfEventObjects", "complexEventObject"]
}

=== fpoulin/json-shapeshifter/src/main/resources/payloads/testComplex.json
{
	"someEventString": "someValue",
	"someEventInteger": 1,
	"someEventStringArray": [
		"someEventValue1", "someEventValue2", "someEventValue3", "someEventValue4"
	],
	"someEventIntegerArray": [
		1, 2, 3, 4, 5, 6, 7, 8, 9
	],
	"simpleEventObject": {
		"stringEventProperty": "someEventValue",
		"integerEventProperty": 1
	},
	"arrayOfEventObjects": [
		{
			"stringEventProperty": "someEventValue1",
			"integerEventProperty": 1
		},
		{
			"stringEventProperty": "someEventValue2",
			"integerEventProperty": 2
		},
		{
			"stringEventProperty": "someEventValue3",
			"integerEventProperty": 3
		}
	],
	"complexEventObject": {
		"objectEventProperty": {
			"stringEventProperty": "someEventValue",
			"integerEventProperty": 1
		},
		"arrayEventProperty": [
			{
				"stringEventProperty": "someEventValue1",
				"integerEventProperty": 1
			},
			{
				"stringEventProperty": "someEventValue2",
				"integerEventProperty": 2
			},
			{
				"stringEventProperty": "someEventValue3",
				"integerEventProperty": 3
			}
		]
	}
}
